@file:JvmName("AnalyticsConstants")
package org.dhis2.utils.analytics

const val SYNC_MANAGER_FRAGMENT: String = "SyncManagerFragment"
const val LOG_IN = "Log in"
const val LOGIN = "login"
const val CLICK = "CLICK"
const val LOGIN_ACTIVITY = "LoginActivity"
const val ABOUT_FRAGMENT = "About"
const val ACCOUNTRECOVERY = "Account recovery"
const val ACCOUNT_RECOVERY = "account_recovery"
const val FORGOT_YOUR_CODE = "Forgot your code?"
const val FORGOT_CODE = "forgot_code"
const val QR_URL_SCANNER = "QR Url Scanner"
const val SERVER_QR_SCANNER = "server_url_qr_scanner"
const val UNLOCKSESSION = "Unlock session"
const val UNLOCK_SESSION = "unlock_session"
const val BLOCK_SESSION = "block_session"
const val CLOSE_SESSION = "close_session"
const val SHOW_HELP = "show_help"
const val SELECT_PROGRAM = "select_program"
const val TYPE_PROGRAM_SELECTED = "type_program"
const val SYNC_GRANULAR = "sync_granular"
const val SYNC_GRANULAR_ONLINE = "sync_online"
const val SYNC_GRANULAR_SMS = "sync_sms"
const val SYNC_DATA = "sync_data"
const val TYPE_SYNC = "type_sync"
const val SYNC_METADATA = "sync_metadata"
const val SYNC_DATA_NOW = "sync_data_now"
const val SYNC_METADATA_NOW = "sync_metadata_now"
const val CONFIRM_DELETE_LOCAL_DATA = "confirm_delete_local_data"
const val CONFIRM_RESET = "confirm_reset"
