package org.dhis2.usescases.enrollment

import androidx.compose.ui.test.junit4.createComposeRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.dhis2.lazyActivityScenarioRule
import org.dhis2.usescases.BaseTest
import org.junit.Ignore
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class EnrollmentTest : BaseTest() {

    @get:Rule
    val ruleEnrollment = lazyActivityScenarioRule<EnrollmentActivity>(launchActivity = false)

    @get:Rule
    val composeTestRule = createComposeRule()

    @Ignore("Not working in new form, fixed on ANDROAPP-6179")
    @Test
    fun shouldShowDateEditionWarningMessage() {
        setupCredentials()
        setDatePicker()
        prepareTeiWithAutogeneratedEvents(ruleEnrollment)

        enrollmentFormRobot {
//            clickOnDateOfBirth()
            changePickerDate()
            clickOnAcceptEnrollmentDate()
            checkDateWarningIsDisplayed()
        }
    }
}
