package org.dhis2.usescases.enrollment

import android.content.Intent
import androidx.test.core.app.ApplicationProvider
import org.dhis2.LazyActivityScenarioRule

private const val CHILD_PROGRAM_UID_VALUE = "IpHINAT79UW"
private const val ENROLLMENT_VALUE_AUTOGENERATED_EVENTS = "LZg2cOvrAlU"

fun startEnrollmentActivity(
    programUid: String?,
    enrollmentUid: String?,
    enrollmentMode: EnrollmentActivity.EnrollmentMode,
    forRelationship: Boolean,
    rule: LazyActivityScenarioRule<EnrollmentActivity>
) {
    Intent(
        ApplicationProvider.getApplicationContext(),
        EnrollmentActivity::class.java
    ).apply {
        putExtra(EnrollmentActivity.ENROLLMENT_UID_EXTRA, enrollmentUid)
        putExtra(EnrollmentActivity.PROGRAM_UID_EXTRA, programUid)
        putExtra(EnrollmentActivity.MODE_EXTRA, enrollmentMode.name)
        putExtra(EnrollmentActivity.FOR_RELATIONSHIP, forRelationship)
    }.also {
        rule.launch(it)
    }
}

fun prepareTeiWithAutogeneratedEvents(rule: LazyActivityScenarioRule<EnrollmentActivity>) {
    startEnrollmentActivity(
        CHILD_PROGRAM_UID_VALUE,
        ENROLLMENT_VALUE_AUTOGENERATED_EVENTS,
        EnrollmentActivity.EnrollmentMode.CHECK,
        false,
        rule
    )
}
