package org.dhis2.mobile.aggregates.model

internal sealed class InputType {
    data object Text : InputType()
    data object LongText : InputType()
    data object Letter : InputType()
    data object PhoneNumber : InputType()
    data object Email : InputType()
    data object Boolean : InputType()
    data object TrueOnly : InputType()
    data object DateTime : InputType()
    data object Date : InputType()
    data object Time : InputType()
    data object Number : InputType()
    data object UnitInterval : InputType()
    data object Percentage : InputType()
    data object Integer : InputType()
    data object IntegerPositive : InputType()
    data object IntegerNegative : InputType()
    data object IntegerZeroOrPositive : InputType()
    data object TrackerAssociate : InputType()
    data object Username : InputType()
    data object Coordinates : InputType()
    data object OrganisationUnit : InputType()
    data object Reference : InputType()
    data object Age : InputType()
    data object Url : InputType()
    data object FileResource : InputType()
    data object Image : InputType()
    data object GeoJson : InputType()
    data object MultiText : InputType()
}
