package org.dhis2.data.dhislogic

import java.util.Date
import org.hisp.dhis.android.core.enrollment.Enrollment
import org.hisp.dhis.android.core.period.PeriodType
import org.hisp.dhis.android.core.program.Program
import org.hisp.dhis.android.core.program.ProgramStage

interface EnrollmentEventGeneratorRepository {
    fun enrollment(enrollmentUid: String): Enrollment
    fun enrollmentAutogeneratedEvents(enrollmentUid: String, programUid: String): List<ProgramStage>
    fun enrollmentProgram(programUid: String): Program
    fun firstStagesInProgram(programUid: String): ProgramStage?
    fun firstOpenAfterEnrollmentStage(programUid: String): ProgramStage?
    fun eventExistInEnrollment(enrollmentUid: String, stageUid: String): Boolean
    fun eventUidInEnrollment(enrollmentUid: String, stageUid: String): String
    fun addEvent(
        enrollmentUid: String,
        programUid: String,
        stageUid: String,
        orgUnitUid: String
    ): String

    fun periodStartingDate(periodType: PeriodType, date: Date): Date
    fun setEventDate(eventUid: String, date: Date)
    fun setDueDate(eventUid: String, date: Date, isOverdue: Boolean)
}
