package org.dhis2.form.model

enum class ActionType {
    ON_NEXT,
    ON_FOCUS,
    ON_SAVE,
    ON_TEXT_CHANGE,
    ON_SECTION_CHANGE,
    ON_CLEAR,
    ON_FINISH,
    ON_REQUEST_COORDINATES,
    ON_CANCEL_REQUEST_COORDINATES,
    ON_STORE_FILE,
    ON_ADD_IMAGE_FINISHED,
}
