package org.dhis2.form.model

enum class UiEventType {
    DATE_TIME,
    AGE_CALENDAR,
    AGE_YEAR_MONTH_DAY,
    ORG_UNIT,
    REQUEST_CURRENT_LOCATION,
    REQUEST_LOCATION_BY_MAP,
    ADD_PICTURE,
    SHOW_PICTURE,
    SHOW_DESCRIPTION,
    COPY_TO_CLIPBOARD,
    QR_CODE,
    OPTION_SET,
    ADD_SIGNATURE,
    ADD_FILE,
    OPEN_FILE,
    EMAIL,
    PHONE_NUMBER,
}
