package org.dhis2.form.model

enum class UiRenderType {
    DEFAULT,
    POINT,
    POLYGON,
    MULTI_POLYGON,
    VERTICAL_RADIOBUTTONS,
    HORIZONTAL_RADIOBUTTONS,
    VERTICAL_CHECKBOXES,
    HORIZONTAL_CHECKBOXES
}
