package org.dhis2.ui.theme

import androidx.compose.ui.graphics.Color

val contrastDark = Color(0xB3000000)
val contrastLight = Color(0xE6FFFFFF)

val programColorDark = Color(0xFF00BCD4)
val programColorLight = Color(0xFF84FFFF)

val textPrimary = Color(0xDE000000)
val textSecondary = Color(0x8A000000)
val textSubtitle = Color(0x61000000)
val warningColor = Color(0xFFFF9800)
val errorColor = Color(0xFFE91E63)
val colorPrimary = Color(0xFF2C98F0)

val md_theme_light_primary = Color(0xFF2C98F0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D35)
val md_theme_light_secondary = Color(0xFF4CAF50)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF94F990)
val md_theme_light_onSecondaryContainer = Color(0xFF002204)
val md_theme_light_tertiary = Color(0xFFFF9800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCBE)
val md_theme_light_onTertiaryContainer = Color(0xFF2C1600)
val md_theme_light_error = Color(0xFF2C98F0)
val md_theme_light_errorContainer = Color(0xFFFFFFFF)
val md_theme_light_onError = Color(0xFFFFD9DE)
val md_theme_light_onErrorContainer = Color(0xFF400014)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9DCAFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0062A2)
val md_theme_light_outlineVariant = Color(0xFFC3C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9DCAFF)
val md_theme_dark_onPrimary = Color(0xFF003257)
val md_theme_dark_primaryContainer = Color(0xFF00497C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFF78DC77)
val md_theme_dark_onSecondary = Color(0xFF00390A)
val md_theme_dark_secondaryContainer = Color(0xFF005313)
val md_theme_dark_onSecondaryContainer = Color(0xFF94F990)
val md_theme_dark_tertiary = Color(0xFFFFB870)
val md_theme_dark_onTertiary = Color(0xFF4A2800)
val md_theme_dark_tertiaryContainer = Color(0xFF693C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_error = Color(0xFFFFB2BE)
val md_theme_dark_errorContainer = Color(0xFF660025)
val md_theme_dark_onError = Color(0xFF900038)
val md_theme_dark_onErrorContainer = Color(0xFFFFD9DE)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0062A2)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9DCAFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)
