package org.dhis2.mobile.aggregates.ui.constants

const val SYNC_BUTTON_TAG = "sync_button"
const val INDICATOR_TABLE_TAG = "INDICATOR_TABLE"
const val COLUMN_TOTAL_TAG = "TOTAL_COLUMN_TAG"
const val ROW_TOTAL_TAG = "ROW_TOTAL_TAG"
const val INPUT_DIALOG_TAG = "INPUT_DIALOG_TAG"
const val INPUT_DIALOG_DONE_TAG = "INPUT_DIALOG_DONE_TAG"
const val INPUT_DIALOG_NEXT_TAG = "INPUT_DIALOG_NEXT_TAG"
const val INPUT_DIALOG_DISMISS_TAG = "INPUT_DIALOG_DISMISS_TAG"
const val SAVE_BUTTON_TAG = "SAVE_BUTTON"
const val MANDATORY_FIELDS_DIALOG_OK_BUTTON_TEST_TAG = "MANDATORY_FIELDS_DIALOG_OK_BUTTON_TEST_TAG"
const val VALIDATION_BAR_TEST_TAG = "VALIDATION_BAR_TEST_TAG"
const val VALIDATION_BAR_EXPAND_TEST_TAG = "VALIDATION_BAR_EXPAND_TEST_TAG"
const val COMPLETION_DIALOG_BUTTON_TEST_TAG = "COMPLETION_DIALOG_BUTTON_TEST_TAG"
const val VALIDATION_DIALOG_REVIEW_BUTTON_TEST_TAG = "VALIDATION_DIALOG_REVIEW_BUTTON_TEST_TAG"
const val OPTIONAL_VALIDATION_RULE_DIALOG_ACCEPT_TEST_TAG =
    "OPTIONAL_VALIDATION_RULE_DIALOG_ACCEPT_TEST_TAG"
const val VALIDATION_DIALOG_COMPLETE_ANYWAY_BUTTON_TEST_TAG = "VALIDATION_DIALOG_COMPLETE_ANYWAY_BUTTON_TEST_TAG"
