package org.dhis2.usescases.main.ui.model

import org.dhis2.commons.filters.FilterManager
import org.dhis2.usescases.main.HomeItemData

/**
 * Effects generated by the ViewModel and sent to the UI.
 */
sealed interface HomeEffect {
    data class SingleProgramNavigation(
        val homeItemData: HomeItemData,
    ) : HomeEffect

    data class GoToLogin(
        val accountsCount: Int,
        val isDeletion: Boolean,
    ) : HomeEffect

    data object ShowDeleteNotification : HomeEffect

    data object ShowGranularSync : HomeEffect

    data object BlockSession : HomeEffect

    data object ShowPinDialog : HomeEffect

    data class PeriodFilterRequest(
        val periodRequest: FilterManager.PeriodRequest,
    ) : HomeEffect

    data object OrgUnitFilterRequest : HomeEffect

    data object ToggleSideMenu : HomeEffect

    data object ToggleFilters : HomeEffect
}
