import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    `java-gradle-plugin`
    `maven-publish`
    id("org.jetbrains.kotlin.jvm")
}

// Same coordinates and version as :plugin-sdk — see libs.versions.toml `pluginSdk`.
group = "org.dhis2.mobile"
version = libs.versions.pluginSdk.get()

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    // AGP and KGP are read (never applied) to locate the plugin's AAR and to inspect the
    // consuming project's toolchain. They are `compileOnly` because the consuming build already
    // has them on its buildscript classpath. The Compose plugin is reached reflectively instead:
    // its resource task type is internal and its version constant would inline if referenced.
    compileOnly(libs.gradlePlugin)
    compileOnly(libs.kotlinPlugin)

    testImplementation(libs.test.junit)
    testImplementation(gradleTestKit())
}

gradlePlugin {
    plugins {
        create("pluginBundle") {
            id = "org.dhis2.mobile.plugin-bundle"
            implementationClass = "org.dhis2.mobile.plugin.gradle.PluginBundlePlugin"
            displayName = "DHIS2 Android plugin bundle packaging"
            description =
                "Packages a Kotlin Multiplatform library as a signed DHIS2 Android plugin bundle " +
                "(DEX + Compose resources) and enforces the host's toolchain requirements."
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// The host's toolchain, baked into the published jar.
//
// §5.1 of docs/plugin-system.md is a table of versions a plugin must match. Generating it from
// the same version catalog the host builds with makes that table executable and impossible to
// drift: bump a version here and every plugin author's next build tells them so.
// ──────────────────────────────────────────────────────────────────────────────
val generateHostToolchain by tasks.registering {
    description = "Generates HostToolchain.kt from the host's version catalog."

    val kotlinVersion = libs.versions.kotlin.get()
    val composeVersion = libs.versions.composePluginVersion.get()
    val compileSdk = libs.versions.compileSdk.get()
    val pluginSdkVersion = libs.versions.pluginSdk.get()
    val jvmTarget = JavaVersion.VERSION_17.majorVersion
    // Not the host's minSdk (23): InMemoryDexClassLoader needs API 26, so a plugin cannot go lower
    // even though the app itself supports older devices.
    val minSdkFloor = 26
    val outputDir = layout.buildDirectory.dir("generated/hostToolchain")

    inputs.property("kotlinVersion", kotlinVersion)
    inputs.property("composeVersion", composeVersion)
    inputs.property("compileSdk", compileSdk)
    inputs.property("pluginSdkVersion", pluginSdkVersion)
    inputs.property("jvmTarget", jvmTarget)
    inputs.property("minSdkFloor", minSdkFloor)
    outputs.dir(outputDir)

    doLast {
        val target = outputDir.get().asFile.resolve("org/dhis2/mobile/plugin/gradle")
        target.mkdirs()
        target.resolve("HostToolchain.kt").writeText(
            """
            // Generated by :plugin-sdk-gradle:generateHostToolchain — do not edit.
            package org.dhis2.mobile.plugin.gradle

            /** Versions the DHIS2 Capture App host was built with. */
            internal object HostToolchain {
                const val KOTLIN = "$kotlinVersion"
                const val COMPOSE = "$composeVersion"
                const val COMPILE_SDK = $compileSdk
                const val JVM_TARGET = $jvmTarget
                const val MIN_SDK_FLOOR = $minSdkFloor
                const val PLUGIN_SDK_VERSION = "$pluginSdkVersion"
            }

            """.trimIndent(),
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateHostToolchain)
}
