package org.dhis2.usescases.teidashboard

const val GO_TO_ENROLLMENT = "GO_TO_ENROLLMENT"
const val GO_TO_ENROLLMENT_PROGRAM = "GO_TO_ENROLLMENT_PROGRAM"
const val CHANGE_PROGRAM = "CHANGE_PROGRAM"
const val CHANGE_PROGRAM_ENROLLMENT = "CHANGE_PROGRAM_ENROLLMENT"
