package org.dhis2.commons.filters.periods.model

enum class FilterPeriodType {
    NONE,
    DAILY,
    WEEKLY,
    WEEKLY_WEDNESDAY,
    WEEKLY_THURSDAY,
    WEEKLY_SATURDAY,
    WEEKLY_SUNDAY,
    BI_WEEKLY,
    MONTHLY,
    BI_MONTHLY,
    QUARTERLY,
    QUARTERLY_NOV,
    SIX_MONTHLY,
    SIX_MONTHLY_APRIL,
    SIX_MONTHLY_NOV,
    YEARLY,
    FINANCIAL_APRIL,
    FINANCIAL_JULY,
    FINANCIAL_OCT,
    FINANCIAL_NOV,
}
